swagger: '2.0'
info:
  description: 'Avaliação Prática Lemobs'
  version: '1.0.0'
  title: Desafio API Lemobs

basePath: /v1/

consumes:
  - application/json
produces:
  - application/json

schemes:
  - http

paths:

  # Serviço responsável por cadastrar um novo aluno.  
  /aluno:
    x-swagger-router-controller: aluno
    post:
      tags:
        - Aluno
      parameters:
        - in: body
          name: aluno
          description: Modelo de Aluno
          required: true
          schema:
            $ref: "#/definitions/aluno"        
      responses:
        '201':
          description: Criado (Created)
        '400':
          description: Requisição Inválida (Bad Request)
        '500':
          description: Erro Interno do Servidor (Internal Server Error)    
    get:
      tags:
        - Aluno
      responses:
        '200':
          description: OK
        '500':
          description: Erro Interno do Servidor (Internal Server Error)

  /aluno/{id}:
    x-swagger-router-controller: aluno
    get:
      tags:
        - Aluno
      parameters:
        - in: path
          name: id
          description: ID do Aluno
          required: true
          type: number
      responses:
        '200':
          description: OK
        '500':
          description: Erro Interno do Servidor (Internal Server Error)
    put:
      tags:
        - Aluno
      parameters:
        - in: path
          name: id
          description: ID do Aluno
          required: true
          type: number
        - in: body
          name: aluno
          description: Model do Aluno
          required: true
          schema:
            $ref: "#/definitions/aluno"
      responses:
        '200':
          description: OK
        '404':
          description: Página Não Encontrada (Page Not Found)
        '500':
          description: Erro Interno do Servidor (Internal Server Error)

  /aluno/{id}/endereco:
    x-swagger-router-controller: aluno
    get:
      tags:
        - Aluno
      parameters:
        - in: path
          name: id
          description: ID do Aluno
          required: true
          type: number
      responses:
        '200':
          description: OK
        '404':
          description: Página Não Encontrada (Page Not Found)
        '500':
          description: Erro Interno do Servidor (Internal Server Error)
  /aluno/{nota}/criterio/{criterio}:
    x-swagger-router-controller: aluno
    get:
      tags:
        - Aluno
      parameters:
        - in: path
          name: nota
          description: Nota do critério
          required: true
          type: number
        - in: path
          name: criterio
          description: Critério da Busca
          required: true
          type: string
      responses:
        '200':
          description: OK
        '500':
          description: Erro Interno do Servidor (Internal Server Error)
  /aluno/{nota}/media:
    x-swagger-router-controller: aluno
    get:
      tags:
        - Aluno
      parameters:
        - in: path
          name: nota
          description: Média da Busca
          required: true
          type: number
      responses:
        '200':
          description: OK
        '500':
          description: Erro Interno do Servidor (Internal Server Error)


  /endereco:
    x-swagger-router-controller: endereco
    post:
      tags:
        - Endereco
      parameters:
        - in: body
          name: endereco
          description: Modelo de endereço
          required: true
          schema:
            $ref: '#/definitions/endereco'
      responses:
        '201':
          description: Criado (Created)
        '500':
          description: Erro Interno do Servidor (Internal Server Error)
    get:
      tags:
        - Endereco
      responses:
        '201':
          description: OK
        '500':
          description: Erro Interno do Servidor (Internal Server Error)



  /docs:
    x-swagger-pipe: swagger_raw
    
definitions:
  aluno:
    type: object
    properties:
      id:
        type: number
      nome:
        type: string
      data_nascimento:
        type: string
        format: date
      cpf:
        type: string
      nota:
        type: number
    required:
      - id
      - nome
      - data_nascimento
      - cpf
      - nota
  endereco:
    type: object
    properties:
        id:
          type: number
        rua:
          type: string
        numero:
          type: string
        complemento:
          type: string
        bairro:
          type: string
        aluno_id:
          type: number
    required:
      - id
      - rua
      - bairro
      - aluno_id
        
